spring:
  flyway:
    url: jdbc:mysql://localhost:3306/movieon
    user: joyful
    password: 12345678!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/movieon
    username: joyful
    password: 12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
