spring:
  application:
    name: movie-on
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health
      base-path: /monitoring
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
