version: "3.9"
services:
  db:
    platform: linux/amd64
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ../db/mysql/data:/var/lib/mysql
      - ../db/mysql/config:/etc/mysql/conf.d
      - ../db/mysql/init:/docker-entrypoint-initdb.d
